.PHONY:
all:
	$(MAKE) -C adder
	$(MAKE) -C subtractor
	$(MAKE) -C multiplier
	$(MAKE) -C divider
	$(MAKE) -C comparator

.PHONY:
clean:
	$(MAKE) clean-all -C adder
	$(MAKE) clean-all -C subtractor
	$(MAKE) clean-all -C multiplier
	$(MAKE) clean-all -C divider
	$(MAKE) clean-all -C comparator
